sudo: false
language: c
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]$/
matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.6"
    - os: linux
      arch: arm64
      dist: bionic
      language: python
      python: "3.6"
    - os: linux
      dist: trusty
      language: python
      python: "3.7"
    - os: linux
      arch: arm64
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      dist: trusty
      language: python
      python: "3.8"
    - os: linux
      arch: arm64
      dist: bionic
      language: python
      python: "3.8
script:
  - python run.py deps
  - python run.py ci
